name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Passo 1: Check out o código
    - name: Check out code
      uses: actions/checkout@v2

    # Passo 2: Configurar Python
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Passo 3: Instalar dependências
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Passo 4: Rodar os testes (se houver)
    - name: Run tests
      run: |
        pytest

    # Passo 5: Executar o código
    - name: Run d20 game script
      run: |
        python d20_game.py
